name: Process Chunk

on:
  workflow_dispatch:
    inputs:
      test:
        description: "Run on test schema"
        default: false
        type: boolean
      quality:
        description: 'Quality specifier e.g. "480p,360p,1080p60"'
        default: "480p"
        type: string
      chunk_id:
        description: "Chunk ID to process"
        required: true
        type: string

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
jobs:
  process-chunk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build SFOT container
        run: |
          docker build -t bazaar-ghost-sfot ./sfot

      - name: Process chunk with SFOT
        run: |
          # Create output directory
          mkdir -p ./output

          echo "Processing chunk ${{ inputs.chunk_id }} with test mode: ${{ inputs.test }}"


          # Run SFOT container to process the chunk
          # Container will fetch chunk details and update status internally
          timeout 2420 docker run --rm \
            --network="host" \
            -v "./output:/app/output" \
            -v "./test_data:/app/test_data" \
            -e SUPABASE_URL="$SUPABASE_URL" \
            -e SUPABASE_SECRET_KEY="$SUPABASE_SECRET_KEY" \
            -e CHUNK_ID="${{ inputs.chunk_id }}" \
            -e TEST_MODE="${{ inputs.test }}" \
            -e QUALITY="${{ inputs.quality }}" \
            bazaar-ghost-sfot

          DOCKER_EXIT_CODE=$?

          echo "Docker run exit code: $DOCKER_EXIT_CODE"

          # Exit with the same code as the container
          if [ $DOCKER_EXIT_CODE -eq 0 ]; then
            echo "Processing completed successfully"
            exit 0
          else
            echo "Processing failed with exit code: $DOCKER_EXIT_CODE"
            exit $DOCKER_EXIT_CODE
          fi
